# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Check for updates in ./docs/standard_tables
          command: |
            git fetch origin master:master
            changed_files=$(git diff --name-only master...HEAD | grep '^docs/standard_tables/')
            if [ -n "$changed_files" ]; then
              echo "Changes detected in ./docs/standard_tables folder."
              echo "$changed_files" | while read -r file; do
                if ! awk -F '|' 'NR>2 { if ($3 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) exit 1; if ($4 !~ /^[[:space:]]*[1-4](,[[:space:]]*[1-4])*[[:space:]]*$/) exit 1; if ($5 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) exit 1 }' "$file"; then
                  echo "ERROR: $file does not contain a valid Markdown table with the required format."
                fi
              done
            else
              echo "No changes detected in ./docs/standard_tables folder."
            fi
  # build:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     # Replace this with steps to build a package, or executable
  #     - run:
  #         name: Build an artifact
  #         command: touch example.txt
  #     - store_artifacts:
  #         path: example.txt
  # deploy:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     # Replace this with steps to deploy to users
  #     - run:
  #         name: deploy
  #         command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - test
