# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Fetch updates from origin main branch
          command: |
            git fetch origin master:master
      # Check for changes in docs/standard_tables directory
      - run:
          name: Check for changes in ./docs/standard_tables folder
          command: |
            changed_files=$(git diff --name-only origin/master HEAD | grep '^docs/standard_tables/')
            if [ -n "$changed_files" ]; then
              echo "Changes detected in ./docs/standard_tables folder."
              echo "$changed_files" | while read -r file; do
                awk -F '|' 'NR>2 {
                    if ($5 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) {
                        echo "ERROR: $file - The value in the \"Is the deviation reasonable?\" column must be either \"True\" or \"False\"."
                        exit 1
                    } else if ($6 !~ /^[[:space:]]*[1-4](,[[:space:]]*[1-4])*[[:space:]]*$/) {
                        echo "ERROR: $file - The value in the \"Error Types\" column must be a comma-separated list of numbers from 1 to 4."
                        exit 1
                    } else if ($5 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) {
                        echo "ERROR: $file - The value in the \"Display Free text question?\" column must be either \"True\" or \"False\"."
                        exit 1
                    }
                }' "$file"
              done
            else
              echo "No changes detected in ./docs/standard_tables folder."
            fi
            
  # build:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     # Replace this with steps to build a package, or executable
  #     - run:
  #         name: Build an artifact
  #         command: touch example.txt
  #     - store_artifacts:
  #         path: example.txt
  # deploy:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     # Replace this with steps to deploy to users
  #     - run:
  #         name: deploy
  #         command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - test
