# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Fetch updates from origin main branch
          command: |
            git fetch origin master:master
      # Check for changes in docs/standard_tables directory
      - run:
          name: Check for changes in ./docs/standard_tables folder
          command: |
            changed_files=$(git diff --name-only origin/master HEAD | grep '^docs/standard_tables/')
            if [ -n "$changed_files" ]; then
              echo "Changes detected in ./docs/standard_tables folder."
              echo "$changed_files" | while IFS= read -r file; do
                awk -F '|' 'NR>2 {
                    if (NF != 8) {
                        print "ERROR: " $file " - The line does not contain exactly 8 fields."
                        exit 1
                    }
                    if ($4 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) {
                        $4 = substr($4, index($4, $4), index($4, $4) + length($4) - 1)
                        if ($4 != "True" && $4 != "False") {
                            print "ERROR: " $file " - The value in the \"Display is the deviation reasonable?\" column must be either \"True\" or \"False\"."
                            exit 1
                        }
                    }
                    if ($5 !~ /^[[:space:]]*(([1-4])(,[[:space:]]*[1-4])*)[[:space:]]*$/) {
                        print "ERROR: " $file " - The value in the \"Error Types\" column must be a comma-separated list of numbers from 1 to 4."
                        exit 1
                    }
                    if ($6 !~ /^[[:space:]]*(True|False)[[:space:]]*$/) {
                        $6 = substr($6, index($6, $6), index($6, $6) + length($6) - 1)
                        if ($6 != "True" && $6 != "False") {
                            print "ERROR: " $file " - The value in the \"Display is the deviation reasonable?\" column must be either \"True\" or \"False\"."
                            exit 1
                        }
                    }
                    # Add additional checks for other columns as needed

                }' "$file"
                if [ $? -ne 0 ]; then
                    echo "ERROR: $file does not contain a valid Markdown table with the required format."
                    exit 1
                fi
              done
            else
              echo "No changes detected in ./docs/standard_tables folder."
            fi
            
  # build:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     # Replace this with steps to build a package, or executable
  #     - run:
  #         name: Build an artifact
  #         command: touch example.txt
  #     - store_artifacts:
  #         path: example.txt
  # deploy:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     # Replace this with steps to deploy to users
  #     - run:
  #         name: deploy
  #         command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - test
